# Site settings
baseURL = "https://adam.sr"
languageCode = "en-US"
title = "Adam Sroka"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "sitemap"]
publishDir = "build"

# Enter your tracking code to enable Google Analytics - No, fuck Google Analytics
# googleAnalytics = ""

# Copyright
copyright = "&copy; 2022 Adam Sroka"

[params]

  # Metadata for search engines and social sharing
  author = "Adam Sroka"
  description = "Welcome to Adam Sroka's website!"
  shareImage = "images/preview.jpg"
  twitterHandle = "adamsroka_"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/photo.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = ""

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Contact"

      [[params.links.list1.link]]
        text = "Matrix"
        url = "https://matrix.to/#/@sroka:matrix.org"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:hi@adam.sr"



  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Career"

      [[params.links.list2.link]]
        text = "CV"
        url = "/cv.pdf"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/adam-sroka/"


  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Code"

      [[params.links.list3.link]]
        text = "Codeberg"
        url = "https://codeberg.org/adam"

      [[params.links.list3.link]]
        text = "GitHub"
        url = "https://github.com/adam-sroka/"


  # Links List #4
#  [[params.links]]
#    [params.links.list4]
#      heading = "Composition"
#
#      [[params.links.list4.link]]
#        text = "Blog"
#        url = "/blog"
#
#      [[params.links.list4.link]]
#        text = "Mastodon"
#        url = "https://mstdn.io/users/adamsroka"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
